export const projects = [
  {
    title: 'Take Care',
    description: "Final Project for Le Wagon Bootcamp. Take Care is a platform that helps people to organize and share their personal wishes in the case of death.",
      image: '/images/takecare homepage.png',
    tags: ['RoR','|','JS','|', 'AJAX','|', 'Bootstrap','|', 'HTML','|', 'PostgreSQL'],
    source: 'https://github.com/Malalaya/TakeCare',
    visit: 'https://www.take-care.me/',
    id: 0,
  },
  {
    title: 'Fleur Fairy',
    description:"For our Airbnb mock-up project, our team decided to create a web application that allows users to rent or sell plants and flowers.",
    image: '/images/fleurfairy homepage.png',
    tags: ['RoR','|','CSS','|','Cloudinary','|','Heroku','|','GeoCoding'],
    source: 'https://github.com/FUPharah/rails-fleurfairy',
    visit: 'https://fleur-fairy.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Summarizer',
    description:"This tool is a text summarizer that uses OpenAI GPT-4 to summarize your text for you.",
    image: '/images/summarizer.png',
    tags: ['CSS','|','JavaScript','|','React','|',"GPT-4",'|', 'Redux'],
    source: 'https://github.com/FUPharah/Gpt4summarizer/tree/master/gptsum/gptsummarizer',
    visit: 'https://644535280e762e30b0928fe4--peaceful-longma-40feaa.netlify.app/',
    id: 2,
  },
  {
    title: 'Messaging App',
    description:"A messaging app that allows users to chat with each other in real-time and also to create new chat rooms.",
    image: '/images/msg.png',
    tags: ['Next-JS 13','|','React','|','Tailwind','|','MongoDB','|','Pusher','|','Prisma'],
    source: 'https://github.com/FUPharah/messaging-app',
    visit: 'https://messaging-app-inky.vercel.app/',
    id: 3,
  },
  {
    title: 'E-Commerce Admin Dashboard',
    description:"An e-commerce website admin dashboard is a centralized web interface that provides administrators with tools and features to manage and monitor various aspects of an online store. ",
    image: '/images/admin.png',
    tags: ['Next-JS 13','|','App Router','|','React','|','Tailwind','|','MySQL','|','Prisma'],
    source: 'https://github.com/FUPharah/ecommerce',
    visit: 'https://ecommerce-sooty-gamma.vercel.app/',
    id: 4,
  },
  {
    title: 'E-Commerce Website',
    description:"An e-commerce website connected to the admin dashboard and functions as the front-end or customer-facing side of the online store.",
    image: '/images/shop.png',
    tags: ['Next-JS 13','|','App Router','|','React','|','Tailwind', '|','Clerk'],
    source: 'https://github.com/FUPharah/ecommerce-shop',
    visit: 'https://ecommerce-shop-fawn.vercel.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Got Bachelor of Arts in Chinese Language and Literature' },
  { year: 2018, text: 'Went to China for further studying' },
  { year: 2019, text: "Started Master's Degree in International Trade" },
  { year: 2021, text: 'Got CELTA certificate from Cambridge Assessment' },
  { year: 2022, text: "Completed Master's Degree online while working as a translator and sales representative" },
  { year: 2023, text: 'Started Le Wagon Bootcamp, and graduated' },
];
